In [ ]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
X=df.iloc[:,0:4]
Y=df.iloc[:,4]


In [ ]:
Y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
Y=LabelEncoder().fit_transform(Y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)


In [ ]:
import numpy as np
import heapq
import scipy
y_label=[]
for i in range(len(x_test)):
  X=np.array(x_test.iloc[i,:]).reshape(1,-1)
  ary=scipy.spatial.distance.cdist(x_train,X,metric='euclidean')
  indx=heapq.nsmallest(3,range(len(ary)),ary.take)
  Y_neighbors=[]
  for k in range(len(indx)):
    Y_neighbors.append(y_train[indx[k]])
  y_label.append(max(set(Y_neighbors),key=Y_neighbors.count))

y_label

[0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 1,
 0,
 2,
 0,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 2,
 2,
 1,
 0,
 2,
 2,
 0]

In [ ]:
from sklearn import metrics
print(metrics.classification_report(y_test,y_label))
print(metrics.confusion_matrix(y_test,y_label))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[12  0  0]
 [ 0  7  0]
 [ 0  0 11]]


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
grid_param={ 'n_neighbors':[3,4,5,6,7,8,9,10,11,13],
            'weights':['uniform'],
            'metric':['euclidean']
}
gs=GridSearchCV(KNeighborsClassifier(),grid_param,verbose=1,cv=3,n_jobs=-1)

gs_result=gs.fit(x_train,y_train)
gs_result.best_params_

Fitting 3 folds for each of 10 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  27 out of  30 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    0.2s finished


{'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'uniform'}

In [ ]:
np.sqrt((metrics.mean_squared_error(y_test,y_label)))

0.0