In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


raw_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/weather.csv')
df = raw_data


In [ ]:
x = df.iloc[:,0:4]
y = df.iloc[:,4]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=22)


In [ ]:
train_size=x_train.shape[0]
class_priors={}
for outcome in np.unique(y_train):
    outcome_count = sum(y_train == outcome)    
    class_priors[outcome] = outcome_count / train_size
print(class_priors)

{0: 0.45454545454545453, 1: 0.5454545454545454}


In [ ]:
features=list(x_train.columns)
print(len(x_train))
likelihoods={}
for outcome in np.unique(y_train):
    outcome_count = sum(y_train == outcome)
    for feature in features:
        for feat_value in np.unique(x_train[feature]):
            count=0
            l = list(x_train.index)
            for i in l:
              if(x_train[feature][i]==feat_value and y_train[i]==outcome):
                  count=count+1
            likelihoods[(feature,feat_value,outcome)]=(count+1)/(outcome_count+(len(features)))

print(likelihoods)

11
{('outlook', 'overcast', 0): 0.1111111111111111, ('outlook', 'rainy', 0): 0.3333333333333333, ('outlook', 'sunny', 0): 0.4444444444444444, ('temperature', 'cool', 0): 0.2222222222222222, ('temperature', 'hot', 0): 0.3333333333333333, ('temperature', 'mild', 0): 0.3333333333333333, ('humidity', 'high', 0): 0.5555555555555556, ('humidity', 'normal', 0): 0.2222222222222222, ('windy', False, 0): 0.3333333333333333, ('windy', True, 0): 0.4444444444444444, ('outlook', 'overcast', 1): 0.4, ('outlook', 'rainy', 1): 0.3, ('outlook', 'sunny', 1): 0.2, ('temperature', 'cool', 1): 0.4, ('temperature', 'hot', 1): 0.3, ('temperature', 'mild', 1): 0.2, ('humidity', 'high', 1): 0.3, ('humidity', 'normal', 1): 0.5, ('windy', False, 1): 0.6, ('windy', True, 1): 0.2}


In [ ]:
a=len(np.unique(y_train))
prob=np.ones((a,len(x_test)),dtype=np.float)
print(prob)
for outcome in(np.unique(y_train)):
    outcome_count = sum(y_train == outcome)
    for feature in features:
        l1 = list(x_test.index)

        j=0
        for i in l1:
            print(i, outcome, feature)
            if  (feature,x_test[feature][i],outcome) in likelihoods.keys():
                prob[outcome][j]=prob[outcome][j]*likelihoods[(feature,x_test[feature][i],outcome)]
            else:
                prob[outcome][j]=prob[outcome][j]*(1/(outcome_count+len(features)))
        j = j+1
print(prob)

[[1. 1. 1.]
 [1. 1. 1.]]
7 0 outlook
13 0 outlook
2 0 outlook
7 0 temperature
13 0 temperature
2 0 temperature
7 0 humidity
13 0 humidity
2 0 humidity
7 0 windy
13 0 windy
2 0 windy
7 1 outlook
13 1 outlook
2 1 outlook
7 1 temperature
13 1 temperature
2 1 temperature
7 1 humidity
13 1 humidity
2 1 humidity
7 1 windy
13 1 windy
2 1 windy
[[1.10130124e-06 1.00000000e+00 1.00000000e+00]
 [3.45600000e-07 1.00000000e+00 1.00000000e+00]]


In [ ]:
for i in range(prob.shape[0]):
    prob[i][:]=prob[i][:]*class_priors[i]
 
#Predicting Labels
Y_label=np.zeros(len(y_test))
for i in range(len(x_test)):
    if (prob[1,i]>=prob[0,i]):
        Y_label[i]=1

print(Y_label)

[0. 1. 1.]


In [ ]:
y_test

7     1
13    1
2     1
Name: play, dtype: int64

In [ ]:
from sklearn import metrics 
print(metrics.classification_report(y_test,Y_label)) 
print(metrics.confusion_matrix(y_test,Y_label))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         1.0       1.00      0.67      0.80         3

    accuracy                           0.67         3
   macro avg       0.50      0.33      0.40         3
weighted avg       1.00      0.67      0.80         3

[[0 0]
 [1 2]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import *
cm = confusion_matrix(y_test,Y_label)
acc = accuracy_score(y_test,Y_label)
prec = precision_score(y_test,Y_label)
rec = recall_score(y_test,Y_label)
f1 = f1_score(y_test,Y_label)

print("Confusion matrix: \n", cm,"\n")
print("Accuracy: ", acc)
print("Precision: ", prec)
print("Recall: ", rec)
print("F1 score: ", f1)

Confusion matrix: 
 [[0 0]
 [1 2]] 

Accuracy:  0.6666666666666666
Precision:  1.0
Recall:  0.6666666666666666
F1 score:  0.8


In [ ]:
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]

print("TP: ", TP)
print("TN: ", TN)
print("FP: ", FP)
print("FN: ", FN)



TP:  2
TN:  0
FP:  0
FN:  1


In [ ]:
TPR = TP/(TP+FN)
TNR = TN/(TN+FP) 
FPR = FP/(TP+FN)
FNR = FN/(TN+FP) 

print("TPR: ", TPR)
print("TNR: ", TNR)
print("FPR: ", FPR)
print("FNR: ", FNR)



TPR:  0.6666666666666666
TNR:  nan
FPR:  0.0
FNR:  inf


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in long_scalars
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in long_scalars
  after removing the cwd from sys.path.
